- hosts: localhost
  become: true
  tasks:
  - name: Install Dev Tools
    apt: name={{item}
    with_items:
		- htop
		- git
		- jq
		- zsh
		- fonts-powerline
		- direnv
		- gnome-tweaks
		- golang
		- bison
		- ca-certificates
		- curl
		- gnupg
		- lsb-release
		- apt-transport-https
		- software-properties-common
		- nodejs
		- pip