- hosts: localhost
  become: true
  tasks:
  - name: Install Dev Tools
    dnf: 
      name: '{{item}}'
    with_items:
    - htop
    - git
    - pip
    - jq
    - zsh
    - powerline
    - golang
    - bison
    - gtk3-devel
    - nodejs
    - nsis
    - webkit2gtk3
    - webkit2gtk3-devel
